import type { Listing, BusinessHoursJson } from '@/lib/getListings';

// Hours JSON for a Mon–Fri 9am–5pm business (America/Chicago).
// When the system time is set to a Wednesday at 10:00 AM Chicago → open.
// When set to a Wednesday at 20:00 → closed, opens Thursday at 9am.
export const openHoursJson: BusinessHoursJson = {
  tz: 'America/Chicago',
  hours: {
    mon: [{ open: '09:00', close: '17:00' }],
    tue: [{ open: '09:00', close: '17:00' }],
    wed: [{ open: '09:00', close: '17:00' }],
    thu: [{ open: '09:00', close: '17:00' }],
    fri: [{ open: '09:00', close: '17:00' }],
    sat: null,
    sun: null,
  },
  display: [
    { days: 'Mon – Fri', time: '9am – 5pm' },
    { days: 'Sat – Sun', time: 'Closed' },
  ],
  note: 'Closed on public holidays.',
};

export const mockFields: Listing['fields'] = {
  businessName: 'Green Cycle Co',
  businessDescription: 'Your friendly neighbourhood circular shop.',
  listingPhoto: ['https://example.com/photo.jpg'],
  address: '123 Rundle Mall, Adelaide SA 5000',
  latitude: -34.9285,
  longitude: 138.5999,
  businessEmail: 'hello@greencycle.com.au',
  businessPhone: '08 8000 0000',
  website: 'https://greencycle.com.au',
  contactName: 'Jane Smith',
  contactEmail: 'jane@greencycle.com.au',
  instagramUrl1: 'https://instagram.com/greencycle',
  facebookUrl: 'https://facebook.com/greencycle',
  linkedInUrl: 'https://linkedin.com/company/greencycle',
  tiktokHandle: '@greencycle',
  hasDelivery: true,
  hasPickUp: true,
  hasOnlineShop: true,
  onlineShopLink: 'https://greencycle.com.au/shop',
  category: 'Retail',
  typeOfBusiness: ['Retail'],
  coreMaterialSystem: ['Textiles', 'Paper'],
  enablingSystem: ['Logistics'],
  tags: ['Clothes', 'Books'],
  notableBusinessEvents: ['Swap Meet', 'Repair Café'],
  googleHoursAccurate: 'true',
  businessHours: 'Mon–Fri 9–5',
  hoursJson: openHoursJson,
  inputActions: ['Donate'],
  inputCategories: ['Textiles'],
  inputCategoryIcons: ['donate'],
  inputCategoryOverride: '',
  inputNotes: '',
  outputActions: ['Buy'],
  outputCategories: ['Textiles'],
  outputCategoryIcons: ['buy'],
  outputCategoryOverride: '',
  outputNotes: '',
  serviceActions: ['Repair'],
  serviceCategories: ['General'],
  serviceCategoryIcons: ['repair'],
  serviceCategoryOverride: '',
  serviceNotes: '',
  volunteerOpportunities: false,
  volunteerNotes: '',
  inputActionNames: ['donate'],
  outputActionNames: ['buy'],
  serviceActionNames: ['repair'],
  allActionNames: ['donate', 'buy', 'repair'],
};
